const {Router} = require("express")
const { getAllProducts, createProduct, getProductById, getAllProductsRandomly } = require("../controller/productController")
const getBestSeller = require("../controller/bestSellerController")
const getDcData = require("../controller/dcController")
const getEarbuds = require("../controller/earbudsController")
const getMarvelData = require("../controller/marvelController")
const getNewLaunch = require("../controller/newLaunchController")
const getSaleWithBoat = require("../controller/sailWithboarController")
const getTrendingANC = require("../controller/trendingANCcontroller")
const getTrendingWireless = require("../controller/trendingWirelessController")
const { addToCart, removeFromCart, getCartData, handleCartQuantity } = require("../controller/cartController")

const productrouter = Router()

productrouter.get('/', getAllProducts)
productrouter.post("/add", createProduct)
productrouter.get("/getrandom", getAllProductsRandomly)
// productrouter.get('/bestseller', getBestSeller)
productrouter.get("/dc",getDcData)
// productrouter.get("/earbuds",getEarbuds)
productrouter.get("/marvel",getMarvelData)
productrouter.get("/newlaunch",getNewLaunch)
// productrouter.get("/sailwithboat",getSaleWithBoat)
productrouter.get("/trendingANC",getTrendingANC)
// productrouter.get("/trendingWireless", getTrendingWireless)
productrouter.post("/addToCart", addToCart)
productrouter.post("/removeFromCart", removeFromCart)
productrouter.get("/:userId/cartdata", getCartData)
productrouter.get("/:productId", getProductById)
productrouter.post("/handleCartQuantity",handleCartQuantity)

module.exports = productrouter